name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZWIwM2QzMTItN2E2Zi00ZDM3LWFlODQtNzQyYmI1YWU0ODI4IiwidGVuYW50X2lkIjoiYTQwNzc4NTBhZGQ0ZjllNzE2NDYzY2FjY2ZkYWQwNDE0ZDZkZjFhYWY3ZWIzOGM3MDk2Mzc2NTM3YmEyY2Q2NyIsImludGVybmFsX3NlY3JldCI6ImIxZjlkMWE1LWU5MGYtNDg2OS1hODk3LTc1YmVjNDk4Y2VjNyJ9.ZRLdVLLIhPvOAazI_HSbcs2eAYMHYXgcsdDXlELTkR8"
JWT_SECRET = "mysercetkey4297"