name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiN2QzYjI5MjQtYTM1NC00MTA0LWIxZjctY2UwNmZlYmFlZmExIiwidGVuYW50X2lkIjoiNmIzNWRjYjJlNDhjNjE1NjEwY2U2NGY2ZGE4ZDk2YjQ1MzNhNWU2MGY1ZDFjYjg1Yjk3YzMzMWIxZjBjYzc0OSIsImludGVybmFsX3NlY3JldCI6IjZiYTU0YTE0LWE0YWMtNDIyMS05Yjc0LTAxMjI4MDRmNjE2MiJ9.xQFhOhCx8uP-cx5u-4CAceH-kRGdeHauMrxQ7OkZ7bM"
JWT_SECRET = "mysercetkey"